version: '4.16.2'

services:
    database:
        image: mysql:8.0.22
        volumes:
            - .docker/data/db:/var/lib/mysql:cached
        command: --default-authentication-plugin=mysql_native_password --log-bin-trust-function-creators=on
        restart: always
        platform: linux/x86_64
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: budgetStuff
            MYSQL_USER: test_user
            MYSQL_PASSWORD: pass
        ports:
            - '3306:3306'
